### ISSUE TITLE
any chance of creating a WebStorm repo and snippets?

### ISSUE THREAD

**Issue by born2net** [magarcia/vim-angular2-snippets#1]
any chance of creating a WebStorm repo and snippets?

regards

Seab

**Comment by magarcia** [comment]
Sorry @born2net I don't know how to make snippets for WebStorm. This repo is based on [johnpapa/vscode-angular2-snippets](https://github.com/johnpapa/vscode-angular2-snippets), you're free to try to make your own.
Problably this can be helpful johnpapa/angular-styleguide#711

**Comment by born2net** [comment]
got it tx!
